      double precision barn,aml,aml2,al2,amt,
     &pi,pi2,alfa,amp,amh,amhh,amhu,ampi
      double precision amp2,ap,ap2,amc2,amlep(2)
      integer isf20,i2(8),i1(8)
      data barn/0.389379d+6/,
     &pi/3.1415926d0/,alfa/0.729735d-2/,
     &amp/0.938272d0/,ampi/0.1395675d0/
	data amlep/0.511000d-3,0.10565d0/
      data isf20/4/
      data i2/1,1,1,1,1,1,1,1/
      data i1/3,3,3,3,3,3,3,3/

      common/consts/amhh,amhu,amh,ap,ap2,amp2,amc2,pi2,aml,aml2,al2,amt
